### ISSUE TITLE
MW 1.26alpha master Metrolook - parameters dont work

### ISSUE THREAD

**Issue by lagleki** [paladox/Metrolook#107] opened 2015-05-28 18:50 UTC
We use one of the latest builds of MW 1.26alpha and the latest Metrolook:
http://mw.lojban.org

Setting ```$wgMetrolookLogo = false;``` doesn't disable the logo. Nor other parameters in LocalSettings.php change anything.

Can anyone else confirm it? Is the version of Metrolook for MW 1.25 any safer for using with MW 1.26 alpha?

**Comment by paladox** [comment] 2015-05-28 18:54
Hi I will look into it but 1.25 no because I try to backport changes so they are all the same but some may have different features and 1.25 version will not work in 1.26 alpha because it requires position = top in resource loader.

**Comment by paladox** [comment] 2015-05-28 18:55
And I belive it is a problem with the extension registration I have had this problem with other extensions. please could you set it in the skin.json file saying try or false. since there is a patch trying to fix this.

**Comment by lagleki** [comment] 2015-05-29 06:40
Yes, of course editing skin.json works. Since it's a workaround I'm not closing this issue.

**Comment by paladox** [comment] 2015-05-29 08:39
Ok. you can follow the bug here https://phabricator.wikimedia.org/T99257 and https://phabricator.wikimedia.org/T100767 here.

**Comment by paladox** [comment] 2015-05-30 10:50
This is a know issue. This can stay open till the problem is fixed.

**Comment by paladox** [comment] 2015-06-03 22:07
Partial fix ready it works as in the settings are pre set to true and you can set in false but if settings pre set to false and you do true in localsettings.php It wont work.

**Comment by paladox** [comment] 2015-06-14 17:33
It seems to all work correctly please download MediaWiki wmf 9 for the fix. Closing this as it works for me. Please reopen if it still happends.

**Closed by paladox** 2015-06-14 17:33 UTC
Labels: Bug
